pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "tonuser/mon-frontend"
        REGISTRY_CREDENTIALS = 'dockerhub-creds'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build(DOCKER_IMAGE)
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', REGISTRY_CREDENTIALS) {
                        dockerImage.push('latest')
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'ssh user@server "cd /chemin/deploiement && docker-compose pull && docker-compose up -d"'
            }
        }
    }
}