version: "3.8"
services:
  backend:
    image: tonuser/mon-backend:latest
    ports:
      - "5001:5001"
    networks:
      - webnet

  frontend:
    image: tonuser/mon-frontend:latest
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
